### ISSUE TITLE
Implement RGB16 / RGB565

### ISSUE THREAD

**Issue by scls19fr** [JuliaGraphics/ColorTypes.jl#114]
Hello,

following https://github.com/JuliaGraphics/Colors.jl/issues/332 implementing a 2 bytes (16 bits) colors might be considered

Here is a schema for such colors representation
```
1        |1          |        0
5 4 3 2 1|0 9 8 7 6 5|4 3 2 1 0 
---------|-----------|---------
R R R R R|G G G G G G|B B B B B
```

- 5 bits for **red** channel - 32 values

- 6 bis for **green** channel - 64 values (green gets an extra bit because it's the main element of luminance)

- 5 bits for **blue** channel - 32 values

Name|R|G|B|value
----|-|-|-|-----
BLACK|0|0|0|0
WHITE|31|63|31|65535
RED|31|0|0|63488
GREEN|0|63|0|2016
BLUE|0|0|31|31
GRAY|16|33|16|33840
BROWN|23|34|0|48192
YELLOW|31|63|0|65504

Kind regards

**Comment by timholy** [comment]
@scls19fr, if you need this soon I'd advise you to give it a shot yourself. Folks can help review your implementation and give advice.

**Comment by kimikage** [comment]
Btw, there are some 16-bit RGB formats, although the RGB565 is common and we can look on RGB555 as 15-bit RGB (e.g. `RGB15`).  

To make it clear, I think `RGB565` is preferable to `RGB16` for its name, until we start using the 565-bit colors.

**Comment by scls19fr** [comment]
Your are right @kimikage , `RGB565` seems a quite standard naming for such a color representation.

**Comment by kimikage** [comment]
Improvements to the Julia binding of OpenCV are ongoing. I think it would be nice to have color types (e.g. `HSV24`) for the 8-bit pixel format used in OpenCV.
Since the point of those "storage" types is not to add "novel" color types, but to bridge OpenCV and traditional JuliaImages, it would be preferable if `HSV24` and `HSV{Float32}` could be handled equivalently.

I think it's reasonable to include `RGB565` and so on in the add-on package which provides such storage types. It should be `RGB565 <: AbstractRGB{N0f8}` as well as `HSV24 <: Color{Float32, 3}`.

**Comment by kimikage** [comment]
I'm not opposed to adding `RGB565`, `RGB332` etc. to ColorTypes.jl, but they are domain specific. Also, I feel that the JuliaImages ecosystem is not mature enough to handle those types.
I'd like to consolidate the near-term discussion (if necessary) into the repository: https://github.com/kimikage/StorageColorTypes.jl
