### ISSUE TITLE
support `float` for Colorant

### ISSUE THREAD

**Issue by johnnychen94** [JuliaGraphics/ColorTypes.jl#123]
With `floattype` introduced in #121, one can promote the image from `Gray{N0f8}` to `Gray{Float32}` easily with the following code:

```julia
floattype(eltype(img)).(img)
```

While a perhaps more natural way of doing this is to extend `float` for `Colorant` and use

```julia
float.(img) # promote Gray{N0f8} to Gray{Float32}
```

P.S. I opened this issue because I made a silly mistake of not `import Base: float`. PR #124 achieves this.

**Comment by johnnychen94** [comment]
This feature should be implemented in `ImageCore`, close it now.

**Comment by myrddin89** [comment]
I leave a comment here because I just found out that the current situation may introduce some inconsistencies. 
The problem is that code that loads only `ColorTypes` can break when also `ImageCore` is loaded. With `ColorTypes` one has 
`float(Gray(x)) = x`, while `ImageCore` makes it invariant.

This can be annoying when a library does not force dependence on either of those packages. Surely, one can always solve this issue by applying `channelview` first.

For instance, in my specific case, I had this code `floor(Int, x)` where `x` can be any numeric type, but also a grayscale color. When `x` is of type `Gray`, one can use `float(x)` to get the underlying floating type using `ColorTypes`; this clearly breaks when `ImageCore` is also loaded.

The ideal solution would to be to have a generic way to extract the underlying floating type (I mean, without relying on `gray` which adds the necessity to depend on `ColorTypes`). A workaround can be to convert with an explicit call to `AbstractFloat`, but I am not sure this is ideal.
So my question is, what is the suggested way to come around similar situations?

**Comment by johnnychen94** [comment]
To get the float type of the raw datatype, use: `float(eltype(CT))` (although #184 is proposing to not abuse the name `eltype`)

The usage `floor(Int, x)` with `x` as a `Colorant` is a typical case that should be split into two stages, depending on how we(coders) answer the question: are we still in the colorant scope?

Because if we are still in colorant scope, there's no need to make it an `Integer` -- `floor(x)` should be sufficient and it already works.  Note that `N0f8` from FixedPointNumbers is introduced here to unify the ambiguity of the magical `255` value.

If we're about to leave the colorant scope, then you can unwrap the Colorant type. As you already find out, use `gray(x)` to get the raw data (For RGB image, it can be `red(x), green(x), blue(x)`).

**Comment by myrddin89** [comment]
Yes in my case I’m no more in the colorant scope, probably. But, still, I wonder if it would be possible to support a grayscale image without having to rely on `ColorTypes` and derivates, like `ColorVectorSpace`. My point is that I would like to not have to depend on these packages in library code. 

Of course, one can convert the image first, but it adds boilerplate code that could be avoided. But maybe there is no general way to safely ensure that everything works as expected.

**Comment by myrddin89** [comment]
For example, one could say that `floor(Int, x)` should always return an Int as this is the type we specified. Right now, it attempts to create a `Gray{Int}`.

**Comment by johnnychen94** [comment]
My point is that Int and UInt8 are intentionally not supported because it cause confusions about what 255 is(white? overexposed?). Oh the other hand, float types are allowed and work generally well with JuliaImages.

**Comment by johnnychen94** [comment]
there is no Gray{Int} thing.

**Comment by myrddin89** [comment]
Yes, of course.
I’m starting to think that perhaps I was confused by the fact that when x is an `AbstractFloat`, Gray(x) is allowed for whatever x.
What I was thinking is that one could have defined `floor(Int, Gray(x)) == floor(Int, x)` when x is an `AbstractFloat`.

**Comment by johnnychen94** [comment]
I see. Yes, the semantics of floor(Int, ) is a bit different from float here.

It sounds no harm to add floor(::Gray) and floor(Int, ::Gray) support. But since most images are in 0-1 domain, I think it won't be very much useful in practice.

Do you want to make a PR for this? It should be just a few lines and a few tests.

**Comment by myrddin89** [comment]
Yes will do, thanks. I just don’t know much of the internals but I can figure it out.

**Comment by myrddin89** [comment]
Sorry, but I feel this would require more thoughts, as per JuliaGraphics/ColorVectorSpace.jl/pull/131 and JuliaGraphics/ColorVectorSpace.jl/issues/126.

There it has been explicitly defined `floor(Int, Gray(x)) == Gray{Int}(floor(gray(x)))`, as well for other mathematical operations.

We could change that, but I am not sure if this would be desirable.

**Comment by johnnychen94** [comment]
I'm supporting of changing it.
