### ISSUE TITLE
define more conversions

### ISSUE THREAD

**Issue by alanedelman** [JuliaGraphics/ColorTypes.jl#15]
Some code that used to work with the old Images and Color packages just stopped working because Colors no longer allows me to assign `RGB(1,1,1)` to an image of `RGB4{U8}`:
```jl
`convert` has no method matching convert(::Type{RGB4{UfixedBase{Uint8,8}}}, ::RGB{Float64})
```
Is there any reason why we can't have this and similar conversion routines?

cc: @stevengj

**Comment by timholy** [comment]
I can't replicate, can you give a complete example?
```jl
julia> using ColorTypes

julia> c = RGB4(1,1,1)
RGB4{U8}(1.0,1.0,1.0)

julia> convert(RGB, c)
RGB{U8}(1.0,1.0,1.0)

julia> c = RGB4{Float64}(1,1,1)
RGB4{Float64}(1.0,1.0,1.0)

julia> convert(RGB, c)
RGB{Float64}(1.0,1.0,1.0)

julia> c = RGB(1,1,1)
RGB{U8}(1.0,1.0,1.0)

julia> convert(RGB4, c)
RGB4{U8}(1.0,1.0,1.0)

julia> c = RGB{Float64}(1,1,1)
RGB{Float64}(1.0,1.0,1.0)

julia> convert(RGB4, c)
RGB4{Float64}(1.0,1.0,1.0)
```

**Comment by stevengj** [comment]
@alanedelman, I can't replicate on my machine.  I recall that you were reading a JPEG file and then trying to alter some of its pixels, but this works for me:
```jl
using Images, Colors
sgj = imread(download("http://math.mit.edu/~stevenj/sgj-large.jpg"))
sgj[1,1] = RGB(1,1,1)
```
Can you try it and see whether it works for you?

(I recall that I had to downgrade your version of Images.jl slightly because the latest version wasn't installing correctly — some weird ImageMagick error was coming up when I tried to display an image, and we didn't have time to track it down — so maybe that is the culprit?)
